### ISSUE TITLE
[FEATURE] Spring Boot starter for Google Vertex AI Gemini

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1167]
Spring Boot starter should be added for the [langchain4j-vertex-ai-gemini](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-vertex-ai-gemini) module.
Repository: https://github.com/langchain4j/langchain4j-spring
Examples of existing Spring Boot starters: [langchain4j-open-ai-spring-boot-starter](https://github.com/langchain4j/langchain4j-spring/tree/main/langchain4j-open-ai-spring-boot-starter), [langchain4j-anthropic-spring-boot-starter](https://github.com/langchain4j/langchain4j-spring/tree/main/langchain4j-anthropic-spring-boot-starter)

**Comment by musamakhan201** [comment]
> Spring Boot starter should be added for the [langchain4j-vertex-ai-gemini](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-vertex-ai-gemini) module. Repository: https://github.com/langchain4j/langchain4j-spring Examples of existing Spring Boot starters: [langchain4j-open-ai-spring-boot-starter](https://github.com/langchain4j/langchain4j-spring/tree/main/langchain4j-open-ai-spring-boot-starter), [langchain4j-anthropic-spring-boot-starter](https://github.com/langchain4j/langchain4j-spring/tree/main/langchain4j-anthropic-spring-boot-starter)

When i am trying to push the code on a new branch after making the changes so that i can create a merge request its showing the below error:

11:51:21.478: [langchain4j] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/vertix-ai-gemini-spring-boot-starter:refs/heads/vertix-ai-gemini-spring-boot-starter --set-upstream
remote: Permission to langchain4j/langchain4j.git denied to musamakhan201.
fatal: unable to access 'https://github.com/langchain4j/langchain4j.git/': The requested URL returned error: 403

**Comment by langchain4j** [comment]
@musamakhan201 please make a fork of the lc4j repo and push there, then open a PR
