### ISSUE TITLE
[BUG] PrompTemplate decoding

### ISSUE THREAD

**Issue by AbdullahGheith** [langchain4j/langchain4j#117]
I seem to have problem with PrompTemplates.

When i do the .apply(), new lines gets decoded to ```&#10;```

This makes GPT unable to answer my questions.

My prompttemplates gets resolved into this:

```
Prompt:
'How big is the apartment?'

Context:
'area in m2: 85&#10;&#10;'

```

GPT responds that it doesnt know.

Of course i could sanitize my results before storing them in the vector database. But this seems unintentional.

(Note: this a fictional question and the response is 85 from gpt. In reality, when context is much longer (and contains many more ```&#10;```, it gives me the "You havent specified the size".)

**Comment by langchain4j** [comment]
@AbdullahGheith good catch, thanks for reporting! It turns out that this is how mustache works (we use it under the hood). This is indeed not obvious. I will look into how to better "fix" it a bit later, but for now, you can use triple braces like this: {{{key}}}, this way it should not convert newlines into `&#10;`.

**Comment by AbdullahGheith** [comment]
i will try, thx :)

**Comment by langchain4j** [comment]
Fixed by https://github.com/langchain4j/langchain4j/pull/408
