### ISSUE TITLE
[FEATURE] Gemini — Add a logging request / response option in the builder

### ISSUE THREAD

**Issue by glaforge** [langchain4j/langchain4j#1270]
It's sometimes difficult to know what's going on with the exchanges between an application and a model.

This feature request is about adding a `logRequestAndResponse()` method to `VertexAiGeminiChatModel` and `VertexAIGeminiStreamingChatModel`.

**Comment by langchain4j** [comment]
Would be nice to have separate `logRequests()` and `logResponses()`, if possible.

**Comment by glaforge** [comment]
I followed some models that implemented `logRequestsAndResponse()` like Azure OpenAI. 
Different models seem to do different things here: I see `logRequests()`, `logRequests(Boolean)`, `logRequestsAndResponses(Boolean)`, or sometimes with primitive `boolean`.
Maybe at some point we should have some interface that models should implement?
In my case, I also log system instructions separately, as they are defined on the generative model configuration.
So should I have three methods: `logRequests()`, `logResponses()`, and `logSystemInstructions()`? Or I guess I would always log the system instructions when log requests is enabled.
Do you prefer `logRequests()` (no-args) or `logRequests(Boolean)`?

**Comment by langchain4j** [comment]
AFAIK only Azure models have `logRequestsAndResponses()` because they can't separate them.
All other `*Model` classes should have `logRequests(Boolean)`.
`logRequests()` or `logRequests(boolean)` can be used in clients for simplicity.

Please use `logRequests(Boolean)` and `logResponses(Boolean)` if possible. If not, then `logRequestsAndResponses()`.
System instructions should ideally be logged with the request.

**Comment by glaforge** [comment]
Thanks for the advice and suggestions.
I'll update my (upcoming) PR accordingly.

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1278
