### ISSUE TITLE
[QUESTION] - Dependencies management with a multi-modules project

### ISSUE THREAD

**Issue by clun** [langchain4j/langchain4j#142]
As a developer to use the library i import:

```xml
<dependency>
  <groupId>dev.langchain4j</groupId>
  <artifactId>langchain4j</artifactId>
  <version>${langchain4j.version}</version>
</dependency>
```

But this module drags code associated with **every single store technology** (milvius, weaviate etc...). Even if it is "just" the store class and POJO, some can be in conflict with each other. For instance, the Elastic needs Jackson whereas json is used everywhere.

![Screenshot 2023-08-29 at 14 30 56](https://github.com/langchain4j/langchain4j/assets/726536/e970dd09-3cba-4147-b775-e371d629c937)

Instead of loading [implementation dynamically](https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStore.java#L35) and changing the core for each new vector store why not keeping only the interfaces in core and pushing implementations to the dedicated modules ?

A developer could then only import the module `langchain4j-milvius` and the core will be loaded by transitivity. Think about how spring-data is operating: You have `spring-data-cassandra`, `spring-data-redis` but never import jsut `spring-data`,  it is imported by something else. I know python doing some FAT libraries but here decoupling is more java-ish.

So as refactoring actions would be:
- Most of the code from the module `langchain` could go to `langchain-core` 
- Each store implementation are moved to their module.

As stated in the title it is more an open discussion. I think it is still time to operate such refactoring in the `0.x` versions.

**Comment by BOFA1ex** [comment]
Loading required implementation module via `SPI` is much better.

i.e. jackson
```java
new ObjectMapper().findAndRegisterModules();
```

**Comment by langchain4j** [comment]
Hi @clun thanks for your question.

>>Even if it is "just" the store class and POJO, some can be in conflict with each other. For instance, the Elastic needs Jackson whereas json is used everywhere.

Actual implementations (with their dependencies) for each embedding store are currently living in their own modules and `langchain4j` (main dependency) does not depend on them. The only exception is chroma as it does not introduce any new dependencies to the langchain4j module. If you import `langchain4j`, you drag only a few classes for each integration that delegates actual logic to the implementaitons. They are supposed to depend only on default java types or some custom POJOs or enums. So there is no place for Jackson/GSON conflicts, etc. Do you face any conflicts?

>>Instead of loading [implementation dynamically](https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStore.java#L35) and changing the core for each new vector store why not keeping only the interfaces in core and pushing implementations to the dedicated modules ?

The only reason for dynamic loading is to increase the visibility of existing integrations. So that developer can go to the `EmbeddingStore` interface, click and see all available implementations. As long as this approach does not introduce problems for users and developers, I feel like this approach is a low price to pay for increased visibility. Especially considering that there is no extensive documentation yet.

>>A developer could then only import the module langchain4j-milvius and the core will be loaded by transitivity. Think about how spring-data is operating: You have spring-data-cassandra, spring-data-redis but never import jsut spring-data, it is imported by something else.

`langchain4j-milvus` (or others) can be imported as a standalone dependency (it will load `langchain4j-core` transitively) and used in isolation as an embedidng store only, but the idea is that in 95% of cases it will be used as a part of a RAG application, so one will need `langchain4j` (main module) _and_ `langchain4j-milvus`.

>>As stated in the title it is more an open discussion.

Thanks for opening this discussion, I was not sure about the current approach, but did not yet hear good arguments against it or for a better option. Happy to hear your (and others) arguments.

>>I think it is still time to operate such refactoring in the 0.x versions.

If current approach starts to make problems, it can be changed seamlessly and without any changes required from the end users:
- remove all `XxxEmbeddingStore` classes from `langchain4j` module
- rename all `XxxEmbeddingStoreImpl` into `XxxEmbeddingStore` inside each specific module

Personally I do not like dynamic loading, but I see value in increased visibility.
From the perspective of a library user, it is more convenient to see all integrations in one place at all times. Check each integration class for javadocs, see what features are supported, what are not, etc. Each embedding store has it's own specifics.
And then once I try to use one of them, it suggest to import an optional dependency. Copy and paste the dependency from the console into the pom.xml and that's it.

**Comment by langchain4j** [comment]
@BOFA1ex @chenhaoqiang please share your opinions as well

**Comment by BOFA1ex** [comment]
> The only reason for dynamic loading is to increase the visibility of existing integrations. So that developer can go to the EmbeddingStore interface, click and see all available implementations. As long as this approach does not introduce problems for users and developers, I feel like this approach is a low price to pay for increased visibility. Especially considering that there is no extensive documentation yet.

You are right, It allows you to see more quickly which specific implementatio(e.g. milvus) could be used before compilation.

But have u considered that released a version in each times, you need to sync the version of the currently all-integrated modules (there will be :many in the future).

And I don't think the progress of module updates will be consistent in the future.

![image](https://github.com/langchain4j/langchain4j/assets/30573693/1aa12a40-f664-4ec5-9a8a-ca97ffabc22b)

**Comment by clun** [comment]
Thank you @langchain4j for your quick reply and open mind. 

I am also interested in contributing more to this project if I am useful. I am working on a PR to support another vector technology with the implementation of `EmbeddedStore` and `ChatMemoryStore` (code does not lie).

- **Visibility:**: I think the visibility will come through (1) documentation. (2) the github project source organization.  Not so many people will go browsing the code, unfortunately). I am the creator or `ff4j`, can you tell which db is supported https://github.com/ff4j/ff4j. BTW Are you looking to setup a documentation page ? I did that work in the past and can propose a minimal repo something similar to [Awesome Astra](https://awesome-astra.github.io/docs/pages/develop/) fairly quickly.

- @BOFA1ex made a point about all modules not evolving at the same pace but when it comes to shipping you will release a new version with everything included. You do not want to ask yourself questions like is `langchain4j-milvius:0.21.0` supported by `langchain4j-core:0.18.0`.

- **Dependency Injection**: You may want to instantiate a store with DI instead of a constructor with lots of arguments. You should at least allow default constructors.

- **Code Quality**: I am not a big fan of the code below, it is a little smell: either an abstract class is needed somewhere or code organization could be better.

```java
@Override
public String add(Embedding embedding) {
   return implementation.add(embedding);
}

@Override
public void add(String id, Embedding embedding) {
  implementation.add(id, embedding);
}
```

I am a little pushy I realize but i stay open.

**Comment by langchain4j** [comment]
@BOFA1ex updating versions for all modules is a 30-seconds deal (replace everywhere at once), so this is not a problem.
As @clun has mentioned, we are releasing every module with the new version each time, even if there were no changes to that specific module. This makes it easier for users of the library.

**Comment by langchain4j** [comment]
@clun 

> I am also interested in contributing more to this project if I am useful.

Awesome, would be great to have you on board!

> I am working on a PR to support another vector technology with the implementation of EmbeddedStore and ChatMemoryStore (code does not lie).

Nice, which one(s)?

> I think the visibility will come through (1) documentation. (2) the github project source organization. Not so many people will go browsing the code, unfortunately)

For the long-term, when the project will stabilize, I completely agree. But at the moment new integrations are added pretty fast and we have no documentation yet, so this becomes an issue. Do you think current approach is causing troubles and needs a change asap? If no, I would put it in the backlog, there are lots of things in the issues that need addressing ...

> I am the creator or ff4j, can you tell which db is supported https://github.com/ff4j/ff4j.

Not sure I understand the question. Do you mean which vector stores are currently supported in langchain4j? chroma, milvus, pinecone, weaviate. vespa and elastic are currently in progress, will be merged soon.

> BTW Are you looking to setup a documentation page ?

Yes, I was planning to focus next week solely on writing documentation, getting-started guides, etc.

> I did that work in the past and can propose a minimal repo something similar to [Awesome Astra](https://awesome-astra.github.io/docs/pages/develop/) fairly quickly.

That would be awesome!

> @BOFA1ex made a point about all modules not evolving at the same pace but when it comes to shipping you will release a new version with everything included. You do not want to ask yourself questions like is langchain4j-milvius:0.21.0 supported by langchain4j-core:0.18.0.

Agree, that's what we are doing now.

> Dependency Injection: You may want to instantiate a store with DI instead of a constructor with lots of arguments. You should at least allow default constructors

Please help me understand this use case better. How all implementation-specific parameters (e.g. url, api keys, etc) will be set up in this case? In my understanding each EmbeddingStore implementation requires different parameters and should be initialized in one place all at once. So, for example with spring:
```java
@Bean
EmbeddingStore<TextSegment> embeddingStore() {
    return new ChromaEmbeddingStore(<chroma-specific-parameters>);
}
```

> Code Quality: I am not a big fan of the code below, it is a little smell: either an abstract class is needed somewhere or code organization could be better.

Good point, will refactor it soon.

**Comment by clun** [comment]
- Technology is [AstraDb Vector Search](https://docs.datastax.com/en/astra-serverless/docs/vector-search/overview.html), it can be both embedding store and ChatMemoryStore (as very fast).

- I will go ahead and propose a skeleton repository for the documentation then.

- Comment on FF4j was not really a question sorry.
- For dependency injection, you are right we can go with a new 

We could close this ticket.
