### ISSUE TITLE
[FEATURE] Ollama: support tools

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1525]
Ollama is supporting tools now: https://ollama.com/blog/tool-support

While tools can already be used with `langchain4j-open-ai` module, it would be nice to support them in `langchain4j-ollama` module as well.

**Comment by langchain4j** [comment]
Implementation in Quarkus extension: https://github.com/quarkiverse/quarkus-langchain4j/pull/783

**Comment by jprogramista** [comment]
I’ve tried to use these freshly merged tools and encountered some problems. I modified the test OllamaToolChatModelIT and used my locally installed Ollama on Mac (no docker). However, I couldn’t get a response, so I finally examined the requests and responses. It turned out that if I didn’t add tools to the second request, the "tool" role answer was ignored. In the end, I tried the requests in Postman, and it seems they only work if the tools spec is added.
```
{
    "model": "llama3.1",
    "messages": [
        {
            "content": "What is the flight price from New York (NYC) to Los Angeles (LAX)?",
            "role": "user"
        },
        {
            "content": "",
            "role": "assistant",
            "tool_calls": [
                {
                    "function": {
                        "arguments": {
                            "arrival": "LAX",
                            "departure": "NYC"
                        },
                        "name": "get_flight_info"
                    }
                }
            ]
        },
        {
            "content": "{&quot;from&quot;: &quot;NYC&quot;, &quot;to&quot;: &quot;LAX&quot;, &quot;duration&quot;: &quot;15h 30m&quot;, &quot;price&quot;: &quot;150 USD&quot;}",
            "role": "tool"
        }
    ],
    "options": {},
    "stream": false,
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "get_flight_info",
                "description": "Get the flight data",
                "parameters": {
                    "properties": {
                        "arrival": {
                            "description": "The arrival ",
                            "departure": "string"
                        },
                        "departure": {
                            "description": "The departure",
                            "type": "string"
                        }
                    },
                    "required": [
                        "arrival",
                        "departure"
                    ]
                }
            }
        }
    ]
}
```
Answer: "The price of a flight from New York (NYC) to Los Angeles (LAX) is $150 USD. The duration of the flight is approximately 15 hours and 30 minutes."

If I remove tools section and also if I don't have `toolSpecifications` in:
```
Response<AiMessage> secondResponse = ollamaChatModel.generate(messages, toolSpecifications);
```

then I get raw answer: "I can't provide real-time flight prices. However, I can give you some general information about how to find the best deals on flights from NYC to LAX. Would that help?\n}\nHere are a few suggestions:\n\n1. **Use flight comparison websites**: Websites like Google Flights, Skyscanner, or Kayak allow you to compare prices across multiple airlines and find the best deals.\n2. **Book in advance**: Generally, it's cheaper to book flights well in advance (at least 2-3 months before your travel date).\n3. **Consider off-peak seasons**: If possible, try flying during off-peak seasons (like mid-January to mid-March) when prices tend to be lower.\n4. **Look for error fares or sales**: Keep an eye on airline websites and social media for any error fares or special promotions.\n\nKeep in mind that flight prices can fluctuate constantly, so it's always a good idea to compare prices across multiple sources before booking your ticket!"

My setup: ollama version is 0.3.6, Mac M1, llama3.1

**Comment by langchain4j** [comment]
@jprogramista this seems like an issue in Ollama, no?

**Comment by jprogramista** [comment]
@langchain4j Yes, and maybe it's even only MacOSX version issue or local ollama setup, as I suppose IT tests with TestContainers are passing.

I cannot run IT on my machine due to lack of Apple Silicon support - I get:
`Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"write /tmp/ollama630232873/runners/cuda_v11/ollama_llama_server: no space left on device"`
(here is more explanation on it if anyone interested: https://chariotsolutions.com/blog/post/apple-silicon-gpus-docker-and-ollama-pick-two/)

Maybe some other users can confirm if it works for them, w/o providing `toolSpecifications` in 2nd request. Anyway great work!

**Comment by langchain4j** [comment]
@jprogramista could you pleae open an issue on Ollama github?
