### ISSUE TITLE
[FEATURE] OpenAI: Structured Outputs

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1581]
Support OpenAI's Structured Outputs feature: https://openai.com/index/introducing-structured-outputs-in-the-api

**Comment by kappamax** [comment]
Unfortunately switching to the model to `gpt-4o-2024-08-06` with response format `json_object` from older models causes the model to return an error due to an issue where `json_object` is actually truncated under the hood to `json` so the new `json_schema` is seen as the same thing without the `struct` header. So this needs to be fixed before `gpt-4o-2024-08-06` becomes `gpt-4o` as any existing prompts using `responseFormat("json_object")` will fail.

**Comment by langchain4j** [comment]
Hi @kappamax, where do you see the truncation?

I've just tested `gpt-4o-2024-08-06` + `json_object` combo and it works fine:

**Request:**
```json
{
  "model": "gpt-4o-2024-08-06",
  "messages": [
    {
      "role": "user",
      "content": "Return json with name John and age 42"
    }
  ],
  "temperature": 0.7,
  "response_format": {
    "type": "json_object"
  }
}
```

**Response:**
```json
{
  "id": "chatcmpl-9vgCu9WAPhErO6x18JzcvtWwVpZOU",
  "object": "chat.completion",
  "created": 1723533968,
  "model": "gpt-4o-2024-08-06",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "\n  {\n    \"name\": \"John\",\n    \"age\": 42\n  }",
        "refusal": null
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 16,
    "completion_tokens": 19,
    "total_tokens": 35
  },
  "system_fingerprint": "fp_2a322c9ffc"
}
```
