### ISSUE TITLE
Ollama: add ChatModelListener support

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1756]
Add `ChatModelListener` support to `OllamaChatModel` and `OllamaStreamingChatModel`.
See `OpenAiChatModel` and `OpenAiStreamingChatModel` as an example.

**Comment by Martin7-1** [comment]
@langchain4j Hi! Could you please assign this to me?

**Comment by langchain4j** [comment]
Tests are already in place, one should just extend `ChatModelListenerIT` and `StreamingChatModelListenerIT`, see `OpenAiChatModelListenerIT` `OpenAiStreamingChatModelListenerIT` as an example.

**Comment by Martin7-1** [comment]
@langchain4j OK! But because `OllamaStreamingChatModel` does not support tool calls, the `StreamingChatModelListenerIT` will be hard to extend.

So, I did a slight change to `StreamingChatModelListenerIT` and `ChatModelListenerIT` so that it can also support models which are not support tool calls yet.
