### ISSUE TITLE
Hugging Face embedding model only support sentence-transformers/all-MiniLM-L6-v2?[FEATURE] 

### ISSUE THREAD

**Issue by caopengan** [langchain4j/langchain4j#198]
I try use BAAI/bge-large-zh-v1.5,but throw Exception:
java.lang.IllegalStateException: Expected a double but was BEGIN_ARRAY at line 1 column 4 path $[0][0]

I found that different models return different types of results.

Do you have any consideration on this question？

**Comment by langchain4j** [comment]
@caopengan No, it is supposed to work for any model. But for some reason HuggingFace API returns response in a different format than usual for this specific model. It seems that they are not doing pooling on their side and return embeddings for each token. In theory we can make a workaround, but this will require some time. And ultimately the problem is on HF side. If you need to use this model, you can [download it in onnx format](https://huggingface.co/Xenova/bge-large-zh-v1.5/resolve/main/onnx/model.onnx) and use it offline with `InProcessEmbeddingModel`. See Custom_In_Process_Embedding_Model_Example [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/embedding/model/InProcessEmbeddingModelExamples.java).

**Comment by caopengan** [comment]
> @caopengan No, it is supposed to work for any model. But for some reason HuggingFace API returns response in a different format than usual for this specific model. It seems that they are not doing pooling on their side and return embeddings for each token. In theory we can make a workaround, but this will require some time. And ultimately the problem is on HF side. If you need to use this model, you can [download it in onnx format](https://huggingface.co/Xenova/bge-large-zh-v1.5/resolve/main/onnx/model.onnx) and use it offline with `InProcessEmbeddingModel`. See Custom_In_Process_Embedding_Model_Example [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/embedding/model/InProcessEmbeddingModelExamples.java).

yeah,thank's,I got it!
