### ISSUE TITLE
[FEATURE] Need method add(String id, Embedding embedding, Embedded embedded) in the EmbeddingStore

### ISSUE THREAD

**Issue by VictorZZZZ** [langchain4j/langchain4j#2106]
interface dev.langchain4j.store.embedding.EmbeddingStore has such method as
`void add(String id, Embedding embedding);`

and

`String add(Embedding embedding, Embedded embedded);`

but there is no method like

`add(String id, Embedding embedding, Embedded embedded)`

I would like to add to my database embedding with my own ID and I want to see the object which was embedded

This will save me from having to go to some other storage to retrieve the Embedded object under  ID.

**Comment by langchain4j** [comment]
Hi @VictorZZZZ, would you like to help us implementing this? 🙏

**Comment by VictorZZZZ** [comment]
> Hi @VictorZZZZ, would you like to help us implementing this? 🙏

Yes. i need this in my project.
I can implement it for OpenSearchEmbeddingStore

**Comment by langchain4j** [comment]
Great! Since `EmbeddingStore` API is already crowded with all the `add`/`addAll` method overloads, what do you think about implementing the following API? 

`EmbeddingAddResult add(EmbeddingAddRequest)`
`EmbeddingAddRequest` will contain all the required data to add: ids, embeddings and segments.
`EmbeddingAddResult` will contain ids of added embeddings.

We could then deprecate all the existing `add`/`addAll` methods (or leave only the most useful).
WDYT?

**Comment by VictorZZZZ** [comment]
> Great! Since `EmbeddingStore` API is already crowded with all the `add`/`addAll` method overloads, what do you think about implementing the following API?
> 
> `EmbeddingAddResult add(EmbeddingAddRequest)` `EmbeddingAddRequest` will contain all the required data to add: ids, embeddings and segments. `EmbeddingAddResult` will contain ids of added embeddings.
> 
> We could then deprecate all the existing `add`/`addAll` methods (or leave only the most useful). WDYT?

Good point, I think that a builder() in the EmbeddingAddRequest will handle all possible combinations in the request to add to EmbedingStore.

I am ready to take on this task

**Comment by langchain4j** [comment]
@VictorZZZZ awesome, then I will assign you, thank you in advance!

**Comment by VictorZZZZ** [comment]
@langchain4j after some research I decided to add EmbeddingRecord object (not EmbeddingAddRequest)
and there are 2 methods in the `EmbeddingStore` interface:

    add(EmbeddingRecord)
    addBatch(List<EmbeddingRecord>)

I also had to implement these methods in all the subclasses for the project to compile.))) I used the existing addInternal methods, but in some places, I had to make adjustments.

It turned out to be a huge Pull Request

**Comment by langchain4j** [comment]
Hi @VictorZZZZ thanks! Could you please explain the reasoning behind adding `EmbeddingRecord` instead of `EmbeddingAddRequest`?

I think `EmbeddingAddRequest` would make it more flexible in the future if we will want to add more things to it.
For example, if/when there will be a batching strategy, it can be added into `EmbeddingAddRequest` as an extra field. With the proposed API, it would require to add more overloaded methods

**Comment by VictorZZZZ** [comment]
> Hi @VictorZZZZ thanks! Could you please explain the reasoning behind adding `EmbeddingRecord` instead of `EmbeddingAddRequest`?
> 
> I think `EmbeddingAddRequest` would make it more flexible in the future if we will want to add more things to it. For example, if/when there will be a batching strategy, it can be added into `EmbeddingAddRequest` as an extra field. With the proposed API, it would require to add more overloaded methods


I did this because the user may want to add one record to the storage, or they may want to add several

For this, I am adding two methods:
add(record)
addBatch(List<Records>) 

If we imagine that we will have a single object, EmbeddingAddRequest, which will have a field such as a List<EmbeddingRecords>, it turns out that to add, for example, one element to the storage, we need to perform too many actions:

    Create an EmbeddingRecord
    Place it in a List
    Create an EmbeddingAddRequest from this
    Call method

Therefore, I made just EmbeddingRecord(id, embedding, embedded) and two methods that add either a single object or a batch of them to the storage. If we want to increase the list of fields, we can easily add them to EmbeddingRecord.


If you want me to use 'EmbeddingAddRequest', please describe how it will look and what methods we should define in the interface for adding objects to the storage.

**Comment by langchain4j** [comment]
I was imagining something like this:

```java
EmbeddingAddRequest request = EmbeddingAddRequest.builder()
    .add(id, embedding, segment) // add a single embedding
    .add(id2, embedding2, segment 2) // add one more
    .addAll(ids, embeddings, segments) // or add multiple at once
    .addAll(embeddings, segments) // add without ids
    .build()

embeddingStore.add(request);
```

This does not seem more verbose IMHO.
And usually user will have a list of embeddings and segments, so it seems that it will be easier to call `.addAll(embeddings, segments)` instead of zipping two lists into a `List<EmbeddingRecord>` to add all embeddings to the store.

> If we want to increase the list of fields, we can easily add them to EmbeddingRecord.

What if the field should be applicable to all records, not to a single one?

**Comment by VictorZZZZ** [comment]
> I was imagining something like this:
> 
> ```java
> EmbeddingAddRequest request = EmbeddingAddRequest.builder()
>     .add(id, embedding, segment) // add a single embedding
>     .add(id2, embedding2, segment 2) // add one more
>     .addAll(ids, embeddings, segments) // or add multiple at once
>     .addAll(embeddings, segments) // add without ids
>     .build()
> 
> embeddingStore.add(request);
> ```
> 
> This does not seem more verbose IMHO. And usually user will have a list of embeddings and segments, so it seems that it will be easier to call `.addAll(embeddings, segments)` instead of zipping two lists into a `List<EmbeddingRecord>` to add all embeddings to the store.
> 
> > If we want to increase the list of fields, we can easily add them to EmbeddingRecord.
> 
> What if the field should be applicable to all records, not to a single one?

I like your solution, 
but I will suggest improving it by combining my approach with yours

```java
EmbeddingRecord.builder()
    .id(1) // nullable (if null, than it will be generated)
    .embedding(e) // nonNull
    .embedded(ebd) // nullable 
    .build()

EmbeddingAddRequest request = EmbeddingAddRequest.builder()
     .add(embeddingRecord) // add a single embedding
     .addAll(listOfEmbeddingRecords) // or add multiple at once
     .build()
```
there is no need to overload add() or addAll() methods with different combinations of parameters

**Comment by langchain4j** [comment]
@VictorZZZZ please comment on this:

> And usually user will have a list of embeddings and segments, so it seems that it will be easier to call .addAll(embeddings, segments) instead of zipping two lists into a List<EmbeddingRecord> to add all embeddings to the store.

---

Let's consider the most common situation:

```java
List<Document> documents = FileSystemDocumentLoader.loadDocuments("/home/langchain4j/documentation");
List<TextSegment> segments = documentSplitter.splitAll(documents);
List<Embedding> embeddings = embeddingModel.embedAll(segments).content();
```
Having this, how code for creating `EmbeddingAddRequest` should look like?

**Comment by VictorZZZZ** [comment]
> @VictorZZZZ please comment on this:
> 
> > And usually user will have a list of embeddings and segments, so it seems that it will be easier to call .addAll(embeddings, segments) instead of zipping two lists into a List to add all embeddings to the store.
> 
> Let's consider the most common situation:
> 
> ```java
> List<Document> documents = FileSystemDocumentLoader.loadDocuments("/home/langchain4j/documentation");
> List<TextSegment> segments = documentSplitter.splitAll(documents);
> List<Embedding> embeddings = embeddingModel.embedAll(segments).content();
> ```
> 
> Having this, how code for creating `EmbeddingAddRequest` should look like?

```java
      var requestBuilder = EmbeddingAddRequest.builder();
      for (int i = 0; i < segments.size(); i++) {
          requestBuilder.add(new EmbeddingRecord<TextSegment>(null, segments.get(i), embeddings.get(i)));
      }
```

I understand What are you talking about! It is not comfortable to write the code like this
But the problem is that we need to be sure about the correspondence of elements with index `i`, and having EmbeddingRecord clearly defines this for us. 
What if we need to save not all segments, but all embeddings?

**Comment by VictorZZZZ** [comment]
But ok. If in usual situation dimensions are matched, we can make only EmbeddingAddRequest

but we have same problem. what methods should be there

 - add(id, embeddng, embedded)
 - add(embedding, embedded)
 - add(embedding)

 - addAll(idList, embeddngList, embeddedList)
 - addAll(embeddingList, embeddedList)
 - addAll(embeddingList)
 
 something like this?
 
 what if in future we will need one more field?

**Comment by langchain4j** [comment]
@VictorZZZZ

> I understand What are you talking about! It is not comfortable to write the code like this
> But the problem is that we need to be sure about the correspondence of elements with index i, and having EmbeddingRecord clearly defines this for us.

I agree that it would be safer to not rely on index, but specify all pair/triplets explicitly using `EmbeddingRecord`. Although in all our implementations, `EmbeddingModel` returns embeddings that correspond to segments, so we should be safe.

The problem is that with the existing APIs, user usually operates with `List<TextSegment>` and `List<Embedding>`.
Perharps `EmbeddingModel` could return an (embedding, segment) tuples instead of embeddings, but I am not ready to do changes to that API right now (but I will consider for the future).

> What if we need to save not all segments, but all embeddings?

What do you mean? Store embeddings without segments? Or store part of segments and all embeddings? This sounds quite strange use case TBH. But if required, user can do 2 calls: one with embeddings and segments, another only with embeddings.


> But ok. If in usual situation dimensions are matched, we can make only EmbeddingAddRequest
> 
> but we have same problem. what methods should be there
> 
> add(id, embeddng, embedded)
> 
> add(embedding, embedded)
> 
> add(embedding)
> 
> addAll(idList, embeddngList, embeddedList)
> 
> addAll(embeddingList, embeddedList)
> 
> addAll(embeddingList)
> 
> something like this?
> 
> what if in future we will need one more field?

Perharps we could allow nulls? In this case it would be only 2 methods:
- add(id, embedding, embedded)
- addAll(ids, embeddings, embeddeds)

Another option:

```
EmbeddingAddRequest.builder()
    .addEmbeddings(embeddings)
    .addSegments(segments)
   .addIds(ids)
   .build()
```
In this case, one does not have to add everything, only what one wants to specify.

But yeah, I agree, this needs further thought and design.
So perharps we can add `addAll(List<String> ids, List<Embedding> embeddings, List<Embedded> embedded)` for the moment and then I will think about new API a bit later. WDYT?

**Comment by VictorZZZZ** [comment]
Ok. As I understand, we just need to add method 

`addAll(List<String> ids, List<Embedding> embeddings, List<Embedded> embedded)` to existing EmbeddingStore interface and implement it?

**Comment by langchain4j** [comment]
@VictorZZZZ yes. Will this method be enough for your needs? Or do you require `add(String id, Embedding embedding, Embedded embedded)` as well?

**Comment by VictorZZZZ** [comment]
> @VictorZZZZ yes. Will this method be enough for your needs? Or do you require `add(String id, Embedding embedding, Embedded embedded)` as well?

))) it's enough. I'll do it
