### ISSUE TITLE
[FEATURE] Add support for Azure AI Search as EmbeddingStore

### ISSUE THREAD

**Issue by vermegi** [langchain4j/langchain4j#422]
**Is your feature request related to a problem? Please describe.**
Currently multiple embedding stores already exist in langchain4j, however, Azure AI Search is not yet supported as EmbeddingStore. This store is often used when implementing RAG on the Azure platform with Azure OpenAI.

**Describe the solution you'd like**
An implementation of https://github.com/langchain4j/langchain4j/blob/main/langchain4j-core/src/main/java/dev/langchain4j/store/embedding/EmbeddingStore.java#L12 using https://learn.microsoft.com/en-us/java/api/com.azure.search.documents?view=azure-java-stable 

**Describe alternatives you've considered**
Getting the relevant documents 'manually' similar to how it's done in https://github.com/langchain4j/langchain4j-examples/blob/d47dbb92e4ab583401731992c5dca91c28c643cf/other-examples/src/main/java/ChatWithDocumentsExamples.java#L68 and then sending these as info to the LLM.

**Comment by langchain4j** [comment]
@jdubois FYI

**Comment by jdubois** [comment]
Thanks @langchain4j !
In fact @vermegi and me discussed it before she created the issue (we both work at Microsoft), and @sinedied (from my team at Microsoft) already did something similar for LangChain JS... So this is our next top item, if we want to integrate the best RAG pattern in Java!
BTW, I just learned at https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-cognitive-search-outperforming-vector-search-with-hybrid/ba-p/3929167 that Azure AI Search would do a better job than traditional vector search engines, so I'm not *just* doing this because we work at Microsoft.

**Comment by langchain4j** [comment]
@jdubois my bad, I did not check @vermegi profile 😆
