### ISSUE TITLE
[FEATURE] Javadoc

### ISSUE THREAD

**Issue by LizeRaes** [langchain4j/langchain4j#502]
Is it possible to publish a first version of the javadoc to github Pages (enabled already) to langchain4j.dev/javadoc? We plan to go online with our general documentation website soon, and would be happy to provide a link to the javadoc, even if still incomplete.
@crutcher I saw you've been adding a lot of javadoc recently, thanks a lot for that! Do you know a good way to get it published given that we have those different modules?

**Comment by Martin7-1** [comment]
Hi @LizeRaes , Maybe you can try [this](https://maven.apache.org/plugins/maven-javadoc-plugin/examples/aggregate.html) to solve multi-modules javadoc generation problem. I try it locally and it works fine. I move `maven-javadoc-plugin` to `langchain4j-aggregator`'s `pom.xml`, now the `pom.xml` seems like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.langchain4j</groupId>
    <artifactId>langchain4j-aggregator</artifactId>
    <version>0.26.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        ...
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>aggregate</id>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                        <phase>site</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.5.0</version>
                <reportSets>
                    <reportSet>
                        <id>aggregate</id>
                        <inherited>false</inherited>
                        <reports>
                            <report>aggregate</report>
                        </reports>
                    </reportSet>
                    <reportSet>
                        <id>default</id>
                        <reports>
                            <report>javadoc</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>

</project>
```

And I run `mvn javadoc:aggregate -DskipTests -pl '!langchain4j-opensearch,!code-execution-engines/langchain4j-code-execution-engine-graalvm-polyglot,!langchain4j-neo4j'` (skip some modules because they are not based on jdk8). And the javadoc is generated in `target`, and looks like this:

<img width="1439" alt="image" src="https://github.com/langchain4j/langchain4j/assets/77151639/8fca0ce2-e15a-47a6-a67e-7b4268576306">

The only problem is: How to execute `mvn javadoc:aggreate` on JDK8-based modules and other jdk versions at the same time. (I am not familiar with this, maybe it needs [maven-toolchains-plugin](https://maven.apache.org/plugins/maven-toolchains-plugin/))

**Comment by LizeRaes** [comment]
Hi @Martin7-1 thanks, that worked like a charm! Will have a look for adding the non-jdk8 ones later.
