### ISSUE TITLE
[BUG] TokenWindowChatMemory does not compute tokens for functioncalling parameters

### ISSUE THREAD

**Issue by chenhaoqiang** [langchain4j/langchain4j#64]
I am using AzureOpenAi, and the program uses TokenWindowChatMemory to control the token capacity: TokenWindowChatMemory.builder().capacityInTokens(4096), but when the number of tokens is almost 4096, the interface returns an error, it seems that OpenAiTokenizer did not calculate the token of functioncalling.

![image](https://github.com/langchain4j/langchain4j/assets/20062034/9531e7d9-4a01-4adf-9ff5-5d071b9f8c5a)

![image](https://github.com/langchain4j/langchain4j/assets/20062034/ed6bd1cf-6ce8-4c4f-98d0-c27c308b5bd2)

My temporary solution is to make the capacityInTokens parameter smaller, such as TokenWindowChatMemory.builder().capacityInTokens(3000).

This does not need to be solved right away, depending on your time, thank you!

**Comment by langchain4j** [comment]
@chenhaoqiang thanks a lot for reporting!
ChatMemory is unaware of tools/functions, it's sole purpose is to track messages. Functions are defined outside of messages, so I am not convinced that this is a bug of TokenWindowChatMemory. But I see your point.
However there is an actual bug in OpenAiTokenizer that does not count function-related fields in AiMessage (function_call.name and function_call.arguments) and ToolExecutionResultMessage (function name) and I am going to fix that asap.

Regarding functions (that are defined outside of messages), I need to know a bit more context in order to help you and make it easier for you and others to use this library.
What is your current/target setup? Are you using AiServices? chains? or building with low-level components (directly using ChatMemory, OpenAiChatModel, etc)?
Thanks

**Comment by chenhaoqiang** [comment]
> @chenhaoqiang thanks a lot for reporting! ChatMemory is unaware of tools/functions, it's sole purpose is to track messages. Functions are defined outside of messages, so I am not convinced that this is a bug of TokenWindowChatMemory. But I see your point. However there is an actual bug in OpenAiTokenizer that does not count function-related fields in AiMessage (function_call.name and function_call.arguments) and ToolExecutionResultMessage (function name) and I am going to fix that asap.
> 
> Regarding functions (that are defined outside of messages), I need to know a bit more context in order to help you and make it easier for you and others to use this library. What is your current/target setup? Are you using AiServices? chains? or building with low-level components (directly using ChatMemory, OpenAiChatModel, etc)? Thanks

Thanks for the reply! I'm using AiServices, such as:
AiServices.builder(Chat.class).chatMemory(
                    DbTokenWindowChatMemory.builder().sessionId(sessionId).capacityInTokens(4096).tokenizer(new OpenAiTokenizer("gpt-3.5-turbo")).build());

**Comment by langchain4j** [comment]
@chenhaoqiang in 0.19.0 `OpenAiTokenizer` now counts all tool/function-related fields in messages. `ChatMemory` does not know about tools, so please estimate how many tokens your tools/functions will consume with `OpenAiTokenizer.estimateTokenCountInTools()` or `OpenAiTokenizer.estimateTokenCountInToolSpecifications()`.

**Comment by chenhaoqiang** [comment]
> @chenhaoqiang in 0.19.0 `OpenAiTokenizer` now counts all tool/function-related fields in messages. `ChatMemory` does not know about tools, so please estimate how many tokens your tools/functions will consume with `OpenAiTokenizer.estimateTokenCountInTools()` or `OpenAiTokenizer.estimateTokenCountInToolSpecifications()`.

thanks!
