### ISSUE TITLE
[FEATURE] OpenAiStreamingChatModel for ConversationalRetrievalChain

### ISSUE THREAD

**Issue by robertmaj90** [langchain4j/langchain4j#65]
Would it be possible to have stream response when chat with documents?

**Comment by langchain4j** [comment]
Hi @robertmaj90 we can add this feature for ConversationalRetrievalChain, but you can already do this with AiServices.
Example of streaming: https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ServiceWithStreamingExample.java
Example of setting up AI Service with retriever: https://github.com/langchain4j/langchain4j-examples/blob/main/spring-boot-example/src/main/java/dev/example/CustomerSupportApplication.java

Please let me know if you still want this in ConversationalRetrievalChain.
Thanks!

**Comment by robertmaj90** [comment]
Hi @langchain4j, thank you for such a quick answer!

Yeah, seems like it's possible, I've just done some test and it works! :) 

Best,
Robert

**Comment by langchain4j** [comment]
@robertmaj90 awesome! Then I am closing this issue. Feel free to reopen or open another one. Cheers!

**Comment by langchain4j** [comment]
@robertmaj90 would you mind sharing what are you building? :) Which feature you foresee you will need in the future? Thanks

**Comment by robertmaj90** [comment]
@langchain4j I'm just experimenting with OpenAI and pdf documents :) As for now seems like I have everything! 
Maybe I would be able to do this ConversationalRetrievalChain for streaming response. Let me know if it's possible to contribute to project :)

**Comment by langchain4j** [comment]
@robertmaj90 sure thing, we would love to get contribution from you!
If you are interested in this, you can for sure add this functionality.
Ideally it would be nice to add streaming support to the `Chain` interface, so that every chain can benefit from it. But it will require some structural changes that I need to think through first.
Maybe you could add a separate `StreamingConversationalRetrievalChain` for the moment and later on we could generalize it?
Please let me know your thoughts and thank you for your interest!

**Comment by robertmaj90** [comment]
sure, that's the way I was thinking about it :) will let you know once it's ready! Thanks!
