### ISSUE TITLE
[BUG] Please set up chatMemory in order to use tools

### ISSUE THREAD

**Issue by chenhaoqiang** [langchain4j/langchain4j#78]
In the single chat scenario, in order to reduce the use of tokens, I did not set chatmemory, and I wanted to use the tool, but I got an error：
![image](https://github.com/langchain4j/langchain4j/assets/20062034/53c9efc0-ec2f-4c88-9c72-dac2568698be)

This doesn't fit my scene 😣

**Comment by langchain4j** [comment]
Hi @chenhaoqiang, ChatMemory is required to use tools. To explain, here is the simple example:

1. User sends a message to the LLM. List of available tools is provided as well.
2. LLM chooses to execute one of the tools and responds with a request to execute a particular tool.
3. Tool is executed and the result is sent back to the LLM.
4. LLM processes tool execution result responds in natural language to the user.

As you can see, on the step 3 LLM should receive not only the result of tool execution, but also the initial message from user (from step 1) and it's request to execute a tool (from step 2). Otherwise, it will not understand what is going on and it's response will be random.

Thus, when using tools, you need to have a ChatMemory, at least MessageWindowChatMemory with capacity 3.

**Comment by chenhaoqiang** [comment]
> Hi @chenhaoqiang, ChatMemory is required to use tools. To explain, here is the simple example:
> 
> 1. User sends a message to the LLM. List of available tools is provided as well.
> 2. LLM chooses to execute one of the tools and responds with a request to execute a particular tool.
> 3. Tool is executed and the result is sent back to the LLM.
> 4. LLM processes tool execution result responds in natural language to the user.
> 
> As you can see, on the step 3 LLM should receive not only the result of tool execution, but also the initial message from user (from step 1) and it's request to execute a tool (from step 2). Otherwise, it will not understand what is going on and it's response will be random.
> 
> Thus, when using tools, you need to have a ChatMemory, at least MessageWindowChatMemory with capacity 3.

Thank you for answering so carefully and patiently! I realized that I had misunderstood 😱

**Comment by langchain4j** [comment]
@chenhaoqiang but you reised a good point! I will update exception message to make this clearer to developers. Thanks
