### ISSUE TITLE
[FEATURE] EmbeddingModel.dimensions()

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#960]
`EmbeddingModel` should have a method that returns dimensions to simplify setting up `EmbeddingStore`

**Comment by jmartisk** [comment]
I'd very much like to have this, because it also allows a way (for Quarkus) to find out if an embedding store is empty or not, and to skip ingesting if it's not empty. That will be very useful for the Easy RAG extension in dev mode to avoid re-ingesting on every restart. See https://github.com/quarkiverse/quarkus-langchain4j/issues/473

(To find out if an embedding store is empty, you have to query it, and to query it, you need some kind of reference embedding, and for that you need to know the dimension)

**Comment by langchain4j** [comment]
PR in progress: https://github.com/langchain4j/langchain4j/pull/1250

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1250
